// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateRelationshipSkills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateRelationshipSkills));
        
        string IMigrationMetadata.Id
        {
            get { return "202108172020011_CreateRelationshipSkills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
